backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "Opportunities" # Used in routes, e.g., /admin/collections/blog

    label: "Opportunities" # Used in the UI
    folder: "content/opportunities" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Layout", name: "layout", widget: "hidden", default: opportunity}
      - {label: "Short Description", name: "shortdescription", widget: "string"}
      - {label: "Featured Image webp", name: "thumbnailwebp", widget: "image"}
      - {label: "Featured Image jpg", name: "thumbnailjpg", widget: "image"}
      - {label: "About the Situation 1", name: "situation1", widget: "string"}
      - {label: "About the Situation 2", name: "situation2", widget: "string"}
      - {label: "About the Situation 3", name: "situation3", widget: "string"}
      - {label: "Opportunity 1", name: "opportunities1", widget: "string"}
      - {label: "Opportunity 2", name: "opportunities2", widget: "string"}
      - {label: "Opportunity 3", name: "opportunities3", widget: "string"}
  - name: "Updates"
    label: "Updates"
    folder: "content/updates"
    create: true
    slug: "{{slug}}"
    fields:
     - {label: "Title", name: "title", widget: "string"}
     - {label: "Layout", name: "layout", widget: "hidden", default: update}
     - {label: "Short Description", name: "shortdescription", widget: "string"}
     - {label: "Content", name: "content", widget: "markdown"}
